[[Reactant]]
arch = "x86_64"
cuda_version = "none"
cxxstring_abi = "cxx11"
git-tree-sha1 = "0771261f96645f63346d3c0cc4b2ed4eaaf70cd0"
gpu = "none"
lazy = true
libc = "glibc"
mode = "opt"
os = "linux"

    [[Reactant.download]]
    sha256 = "36b6081dff402fd86424d387b6b0a294cd4f62f6168d647744ae87172ecb00ea"
    url = "https://github.com/JuliaBinaryWrappers/Reactant_jll.jl/releases/download/Reactant-v0.0.257+0/Reactant.v0.0.257.x86_64-linux-gnu-cxx11-cuda_version+none-gpu+none-mode+opt.tar.xz"
[[Reactant]]
arch = "aarch64"
cuda_version = "none"
cxxstring_abi = "cxx11"
git-tree-sha1 = "fc1b1ab71451e07e8eab1823caf0d7e70d4cd5e2"
gpu = "none"
lazy = true
libc = "glibc"
mode = "opt"
os = "linux"

    [[Reactant.download]]
    sha256 = "f93708020607d5de2831964a4f08c1b2a0be3b4207ad0dcfe23ed23b7e8b764c"
    url = "https://github.com/JuliaBinaryWrappers/Reactant_jll.jl/releases/download/Reactant-v0.0.257+0/Reactant.v0.0.257.aarch64-linux-gnu-cxx11-cuda_version+none-gpu+none-mode+opt.tar.xz"
[[Reactant]]
arch = "x86_64"
cuda_version = "none"
git-tree-sha1 = "b7dc3d118c4abccad0d4729269ff71e26ab82775"
gpu = "none"
lazy = true
mode = "opt"
os = "macos"

    [[Reactant.download]]
    sha256 = "5dd69d5a86b30aa1ae20ce7401ca7af54052df4614060a39e9a08c3b9f64c7db"
    url = "https://github.com/JuliaBinaryWrappers/Reactant_jll.jl/releases/download/Reactant-v0.0.257+0/Reactant.v0.0.257.x86_64-apple-darwin-cuda_version+none-gpu+none-mode+opt.tar.xz"
[[Reactant]]
arch = "aarch64"
cuda_version = "none"
git-tree-sha1 = "9cf3b6927e6cbbf697f37fbd60e57b29fd983693"
gpu = "none"
lazy = true
mode = "opt"
os = "macos"

    [[Reactant.download]]
    sha256 = "d3f1450e090e4e39e0eb3096ffcdf833e628c9203a35da7c760c38e7520d335a"
    url = "https://github.com/JuliaBinaryWrappers/Reactant_jll.jl/releases/download/Reactant-v0.0.257+0/Reactant.v0.0.257.aarch64-apple-darwin-cuda_version+none-gpu+none-mode+opt.tar.xz"
[[Reactant]]
arch = "x86_64"
cuda_version = "none"
cxxstring_abi = "cxx11"
git-tree-sha1 = "c98611119ccf64ca4c9127d6f8b3e6f6531ed55c"
gpu = "none"
lazy = true
mode = "opt"
os = "windows"

    [[Reactant.download]]
    sha256 = "fed67ea64f301ad4993d7b300157908d8da8fdbf9d6a82f2370adf709104f6c7"
    url = "https://github.com/JuliaBinaryWrappers/Reactant_jll.jl/releases/download/Reactant-v0.0.257+0/Reactant.v0.0.257.x86_64-w64-mingw32-cxx11-cuda_version+none-gpu+none-mode+opt.tar.xz"
[[Reactant]]
arch = "x86_64"
cuda_version = "none"
git-tree-sha1 = "c3b77a6b2bebf28be62dce6abd7b4b163d42ddee"
gpu = "none"
lazy = true
mode = "dbg"
os = "macos"

    [[Reactant.download]]
    sha256 = "31606dd95afd7ff5c7f805676602c512a5dee53b3a0703ae2cbd7095a17be582"
    url = "https://github.com/JuliaBinaryWrappers/Reactant_jll.jl/releases/download/Reactant-v0.0.257+0/Reactant.v0.0.257.x86_64-apple-darwin-cuda_version+none-gpu+none-mode+dbg.tar.xz"
[[Reactant]]
arch = "aarch64"
cuda_version = "none"
git-tree-sha1 = "75798eb32b9526ba26ceb72330a06d55b0d94cc4"
gpu = "none"
lazy = true
mode = "dbg"
os = "macos"

    [[Reactant.download]]
    sha256 = "12011c8f5abae4e013c4de76eb757374a242acf810b6c427b640d0fc06b418b1"
    url = "https://github.com/JuliaBinaryWrappers/Reactant_jll.jl/releases/download/Reactant-v0.0.257+0/Reactant.v0.0.257.aarch64-apple-darwin-cuda_version+none-gpu+none-mode+dbg.tar.xz"
[[Reactant]]
arch = "x86_64"
cuda_version = "12.9"
cxxstring_abi = "cxx11"
git-tree-sha1 = "3956f8fab0e21c85a6c9292aa56fe9eb41ef1733"
gpu = "cuda"
lazy = true
libc = "glibc"
mode = "opt"
os = "linux"

    [[Reactant.download]]
    sha256 = "56a4365b711ded112bf5f980bacf4dbfb6e28fb166a6a784823ef351d844f95d"
    url = "https://github.com/JuliaBinaryWrappers/Reactant_jll.jl/releases/download/Reactant-v0.0.257+0/Reactant.v0.0.257.x86_64-linux-gnu-cxx11-cuda_version+12.9-gpu+cuda-mode+opt.tar.xz"
[[Reactant]]
arch = "aarch64"
cuda_version = "12.9"
cxxstring_abi = "cxx11"
git-tree-sha1 = "c69dd0cd526b5313493b668e80a7af2c5e7eca04"
gpu = "cuda"
lazy = true
libc = "glibc"
mode = "opt"
os = "linux"

    [[Reactant.download]]
    sha256 = "4f6f202e56b39a692a87d2af5dfaeaae39bbfd3c745adbeb1387b5580d01e483"
    url = "https://github.com/JuliaBinaryWrappers/Reactant_jll.jl/releases/download/Reactant-v0.0.257+0/Reactant.v0.0.257.aarch64-linux-gnu-cxx11-cuda_version+12.9-gpu+cuda-mode+opt.tar.xz"
[[Reactant]]
arch = "x86_64"
cuda_version = "13.0"
cxxstring_abi = "cxx11"
git-tree-sha1 = "70f535ea0e7324f0d536a3d249b57b63a840afbf"
gpu = "cuda"
lazy = true
libc = "glibc"
mode = "opt"
os = "linux"

    [[Reactant.download]]
    sha256 = "cccc66b7a346817d8c945a816b0dbd87322e970576ebf4040bb4db6bd7b77674"
    url = "https://github.com/JuliaBinaryWrappers/Reactant_jll.jl/releases/download/Reactant-v0.0.257+0/Reactant.v0.0.257.x86_64-linux-gnu-cxx11-cuda_version+13.0-gpu+cuda-mode+opt.tar.xz"
[[Reactant]]
arch = "aarch64"
cuda_version = "13.0"
cxxstring_abi = "cxx11"
git-tree-sha1 = "63d540c70615e3634f4663cad0fae93c3bfd99e0"
gpu = "cuda"
lazy = true
libc = "glibc"
mode = "opt"
os = "linux"

    [[Reactant.download]]
    sha256 = "4f7cde4e54d6429beaed8e8c605f78373ee66a2a31b747f31fbbb6d6cfca1f57"
    url = "https://github.com/JuliaBinaryWrappers/Reactant_jll.jl/releases/download/Reactant-v0.0.257+0/Reactant.v0.0.257.aarch64-linux-gnu-cxx11-cuda_version+13.0-gpu+cuda-mode+opt.tar.xz"
